import type {
  BuildReportInput,
  BuildReportOutput,
  ReportModuleResult,
  ReportStep,
} from "./types.js";

/**
 * Build educational Markdown + CSV (and optional HTML preview) from a sim run
 * trace. Pure function — no React, no I/O.
 */
export function buildReport(input: BuildReportInput): BuildReportOutput {
  const title = input.designTitle.trim() || "Untitled design";
  const includeFullSteps = input.includeFullSteps ?? true;
  const markdown = buildMarkdown(input, title, includeFullSteps);
  const csv = buildCsv(input);
  const htmlPreview = buildHtmlPreview(input, title, includeFullSteps);

  return { markdown, csv, htmlPreview };
}

function buildMarkdown(
  input: BuildReportInput,
  title: string,
  includeFullSteps: boolean
): string {
  const lines: string[] = [
    `# OrbitLab Report — ${title}`,
    "",
  ];

  if (input.runId) lines.push(`**Run ID:** ${input.runId}`);
  if (input.designId) lines.push(`**Design ID:** ${input.designId}`);
  if (input.status) lines.push(`**Status:** ${input.status}`);
  if (input.moduleIds?.length) {
    lines.push(`**Modules:** ${input.moduleIds.join(", ")}`);
  } else if (input.moduleResults?.length) {
    lines.push(
      `**Modules:** ${input.moduleResults.map((m) => m.moduleId).join(", ")}`
    );
  }
  if (input.createdAt) lines.push(`**Created:** ${input.createdAt}`);
  lines.push("");

  lines.push("## Summary metrics", "");
  appendSummaryTable(lines, input.summary);

  if (input.errorMessage) {
    lines.push("## Error", "", input.errorMessage, "");
  }

  if (includeFullSteps) {
    const modules = input.moduleResults ?? [];
    if (modules.length === 0) {
      lines.push(
        "## Calculation steps",
        "",
        "_No module equation steps were provided._",
        ""
      );
    } else {
      lines.push("## Calculation steps", "");
      for (const mod of modules) {
        appendModuleSection(lines, mod);
      }
    }
  }

  lines.push("---", "", `_Generated by OrbitLab report engine._`);
  return lines.join("\n");
}

function appendSummaryTable(
  lines: string[],
  summary: BuildReportInput["summary"]
): void {
  const entries = Object.entries(summary ?? {}).filter(
    ([, v]) => v !== undefined && v !== null
  );
  if (entries.length === 0) {
    lines.push("_No summary metrics._", "");
    return;
  }
  lines.push("| Metric | Value |", "| --- | --- |");
  for (const [key, value] of entries) {
    lines.push(`| ${key} | ${formatMetric(value)} |`);
  }
  lines.push("");
}

function appendModuleSection(lines: string[], mod: ReportModuleResult): void {
  const heading = mod.title?.trim() || mod.moduleId;
  lines.push(`### ${heading}`, "");

  if (mod.steps.length === 0) {
    if (mod.data !== undefined) {
      lines.push("_No equation steps; raw module data:_", "", "```json");
      lines.push(JSON.stringify(mod.data, null, 2));
      lines.push("```", "");
    } else {
      lines.push("_No steps for this module._", "");
    }
    return;
  }

  mod.steps.forEach((step, index) => {
    appendStep(lines, step, index + 1);
  });
}

function appendStep(lines: string[], step: ReportStep, n: number): void {
  lines.push(`#### Step ${n}: ${step.title}`, "");
  if (step.latex?.trim()) {
    lines.push(`$$${step.latex.trim()}$$`, "");
  }
  if (step.prose?.trim()) {
    lines.push(step.prose.trim(), "");
  }
}

function buildCsv(input: BuildReportInput): string {
  const samples = input.samples;
  if (samples && samples.length > 0) {
    const keys = Array.from(
      samples.reduce((set, row) => {
        Object.keys(row).forEach((k) => set.add(k));
        return set;
      }, new Set<string>())
    );
    // Prefer a stable column order: t first, then alphabetical rest
    keys.sort((a, b) => {
      if (a === "t") return -1;
      if (b === "t") return 1;
      return a.localeCompare(b);
    });
    const header = keys.join(",");
    const rows = samples.map((row) =>
      keys.map((k) => formatCsvCell(row[k])).join(",")
    );
    return [header, ...rows].join("\n");
  }

  const summaryKeys = Object.keys(input.summary ?? {}).filter(
    (k) => input.summary?.[k] !== undefined && input.summary?.[k] !== null
  );
  if (summaryKeys.length === 0) {
    const runId = input.runId ?? "";
    const designId = input.designId ?? "";
    const status = input.status ?? "";
    return `runId,designId,status\n${runId},${designId},${status}`;
  }
  const header = ["runId", "designId", "status", ...summaryKeys].join(",");
  const values = [
    input.runId ?? "",
    input.designId ?? "",
    input.status ?? "",
    ...summaryKeys.map((k) => formatCsvCell(input.summary?.[k])),
  ].join(",");
  return `${header}\n${values}`;
}

/**
 * Minimal HTML preview: escaped prose + <pre> for latex.
 * Not a full KaTeX renderer — suitable for in-app collapsible preview.
 */
function buildHtmlPreview(
  input: BuildReportInput,
  title: string,
  includeFullSteps: boolean
): string {
  const parts: string[] = [
    `<article class="orbitlab-report">`,
    `<h1>OrbitLab Report — ${escapeHtml(title)}</h1>`,
  ];

  const meta: string[] = [];
  if (input.runId) meta.push(`Run ID: ${escapeHtml(input.runId)}`);
  if (input.designId) meta.push(`Design ID: ${escapeHtml(input.designId)}`);
  if (input.status) meta.push(`Status: ${escapeHtml(input.status)}`);
  if (meta.length) {
    parts.push(`<p class="meta">${meta.join(" · ")}</p>`);
  }

  parts.push(`<h2>Summary metrics</h2>`);
  const entries = Object.entries(input.summary ?? {}).filter(
    ([, v]) => v !== undefined && v !== null
  );
  if (entries.length === 0) {
    parts.push(`<p><em>No summary metrics.</em></p>`);
  } else {
    parts.push(`<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>`);
    for (const [key, value] of entries) {
      parts.push(
        `<tr><td>${escapeHtml(key)}</td><td>${escapeHtml(formatMetric(value))}</td></tr>`
      );
    }
    parts.push(`</tbody></table>`);
  }

  if (input.errorMessage) {
    parts.push(
      `<h2>Error</h2>`,
      `<p class="error">${escapeHtml(input.errorMessage)}</p>`
    );
  }

  if (includeFullSteps) {
    parts.push(`<h2>Calculation steps</h2>`);
    const modules = input.moduleResults ?? [];
    if (modules.length === 0) {
      parts.push(`<p><em>No module equation steps were provided.</em></p>`);
    } else {
      for (const mod of modules) {
        const heading = mod.title?.trim() || mod.moduleId;
        parts.push(`<section class="module">`);
        parts.push(`<h3>${escapeHtml(heading)}</h3>`);
        if (mod.steps.length === 0) {
          parts.push(`<p><em>No steps for this module.</em></p>`);
        } else {
          mod.steps.forEach((step, i) => {
            parts.push(`<div class="step">`);
            parts.push(
              `<h4>Step ${i + 1}: ${escapeHtml(step.title)}</h4>`
            );
            if (step.latex?.trim()) {
              parts.push(
                `<pre class="latex">${escapeHtml(step.latex.trim())}</pre>`
              );
            }
            if (step.prose?.trim()) {
              parts.push(`<p>${escapeHtml(step.prose.trim())}</p>`);
            }
            parts.push(`</div>`);
          });
        }
        parts.push(`</section>`);
      }
    }
  }

  parts.push(`</article>`);
  return parts.join("\n");
}

function formatMetric(value: unknown): string {
  if (typeof value === "number" && Number.isFinite(value)) {
    return Number.isInteger(value) ? String(value) : value.toFixed(4);
  }
  return String(value);
}

function formatCsvCell(value: unknown): string {
  if (value === undefined || value === null) return "";
  const s = String(value);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
