import { ok, err, type Result } from "@orbitlab/domain";
import type { ExportReportCommand, ReportDto } from "../dto/report-dto.js";
import type { SimRunResultDto } from "../dto/sim-run-dto.js";
import { ApplicationError } from "../errors/application-error.js";

/**
 * Stub report exporter: builds Markdown + CSV strings from a sim run result.
 * PDF / KaTeX full-step templates can replace the body later without changing
 * the use-case surface.
 */
export class ExportReportUseCase {
  async execute(
    command: ExportReportCommand
  ): Promise<Result<ReportDto, ApplicationError>> {
    try {
      const run = command.run;
      if (!run?.id) {
        return err(ApplicationError.validation("run is required"));
      }

      const title =
        command.designTitle?.trim() || `Simulation ${run.designId}`;
      const generatedAt = new Date().toISOString();
      const markdown = buildMarkdown(run, title, command.includeFullSteps ?? false);
      const csv = buildCsv(run);

      const report: ReportDto = {
        runId: run.id,
        designId: run.designId,
        title,
        markdown,
        csv,
        generatedAt,
      };

      return ok(report);
    } catch (e) {
      return err(ApplicationError.fromUnknown(e));
    }
  }
}

function buildMarkdown(
  run: SimRunResultDto,
  title: string,
  includeFullSteps: boolean
): string {
  const lines: string[] = [
    `# OrbitLab Report — ${title}`,
    "",
    `**Run ID:** ${run.id}`,
    `**Design ID:** ${run.designId}`,
    `**Status:** ${run.status}`,
    `**Modules:** ${run.moduleIds.join(", ") || "—"}`,
    `**Created:** ${run.createdAt}`,
    "",
    "## Summary metrics",
    "",
  ];

  const entries = Object.entries(run.summary ?? {}).filter(
    ([, v]) => v !== undefined && v !== null
  );
  if (entries.length === 0) {
    lines.push("_No summary metrics._", "");
  } else {
    lines.push("| Metric | Value |", "| --- | --- |");
    for (const [key, value] of entries) {
      lines.push(`| ${key} | ${value} |`);
    }
    lines.push("");
  }

  if (run.errorMessage) {
    lines.push("## Error", "", run.errorMessage, "");
  }

  if (includeFullSteps) {
    lines.push(
      "## Calculation steps",
      "",
      "_Full equation traces will be filled by the report engine (stub)._",
      ""
    );
    if (run.moduleOutputs) {
      lines.push("### Module outputs", "", "```json");
      lines.push(JSON.stringify(run.moduleOutputs, null, 2));
      lines.push("```", "");
    }
  }

  lines.push("---", "", "_Generated by OrbitLab ExportReportUseCase (stub)._");
  return lines.join("\n");
}

function buildCsv(run: SimRunResultDto): string {
  const samples = run.samples;
  if (samples && samples.length > 0) {
    const keys = Array.from(
      samples.reduce((set, row) => {
        Object.keys(row).forEach((k) => set.add(k));
        return set;
      }, new Set<string>())
    );
    const header = keys.join(",");
    const rows = samples.map((row) =>
      keys.map((k) => formatCsvCell(row[k])).join(",")
    );
    return [header, ...rows].join("\n");
  }

  // Fallback: one-row summary
  const summaryKeys = Object.keys(run.summary ?? {});
  if (summaryKeys.length === 0) {
    return "runId,designId,status\n" + `${run.id},${run.designId},${run.status}`;
  }
  const header = ["runId", "designId", "status", ...summaryKeys].join(",");
  const values = [
    run.id,
    run.designId,
    run.status,
    ...summaryKeys.map((k) => formatCsvCell(run.summary[k])),
  ].join(",");
  return `${header}\n${values}`;
}

function formatCsvCell(value: unknown): string {
  if (value === undefined || value === null) return "";
  const s = String(value);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}
